import logging

# Environment
N_PEG_ROWS = 6
N_PEG_COLS = 37
PEG_RADIUS = 0.065  # 0.022
PEG_EDGE_SPACING = 0.06
PEG_TOP_SPACING = 0.5
PEG_BOTTOM_SPACING = 5

PEG_ROW_SPACING = 0.03
PEG_COL_SPACING = PEG_ROW_SPACING * 2.5

FIG_WIDTH = (
    (N_PEG_COLS - 0.5) * PEG_COL_SPACING
    + (N_PEG_COLS + 1) * 2 * PEG_RADIUS
    + 2 * PEG_EDGE_SPACING
)
FIG_HEIGHT = (
    (N_PEG_ROWS - 1) * PEG_ROW_SPACING
    + N_PEG_ROWS * 2 * PEG_RADIUS
    + PEG_BOTTOM_SPACING
    + PEG_TOP_SPACING
)
FLOOR_DROP = FIG_WIDTH / 1.5
FLOOR_OFFSET = 0.05

# [x, y, radius] of static features
FEATURES = [
    [FIG_WIDTH * 0.10, FIG_HEIGHT * 0.73, FIG_WIDTH * 0.05],
    [FIG_WIDTH * 0.20, FIG_HEIGHT * 0.60, FIG_WIDTH * 0.05],
    [FIG_WIDTH * 0.35, FIG_HEIGHT * 0.45, FIG_WIDTH * 0.05],
    [FIG_WIDTH * 0.50, FIG_HEIGHT * 0.30, FIG_WIDTH * 0.05],
    [FIG_WIDTH * 0.65, FIG_HEIGHT * 0.15, FIG_WIDTH * 0.05],
    [FIG_WIDTH * 0.80, FIG_HEIGHT * 0.40, FIG_WIDTH * 0.05],
    [FIG_WIDTH * 0.90, FIG_HEIGHT * 0.66, FIG_WIDTH * 0.05],
]

FIG_SCALE = 1.5

GRAVITY = -3.0  # -9.8  # m / s^2

# Appearance
BOARD_COLOR = "#222222"
PEG_COLOR = "#2EA3F2"
GROUND_COLOR = "#404243"

# Mechanical properties
PEG_STIFFNESS = 1e4
DAMPING = 1

SPEED_LIMIT = 4.0  # 2.5

# Time control
CLOCK_FREQ_SIM = 1000  # Hertz
CLOCK_PERIOD_SIM = 1 / float(CLOCK_FREQ_SIM)
CLOCK_FREQ_VIZ = 30  # Hertz

# Logging settings
LOGGING_LEVEL_SIM = logging.INFO
LOGGING_LEVEL_VIZ = logging.INFO
