import logging

# Environment
N_PEG_ROWS = 17
N_PEG_COLS = 10
PEG_RADIUS = 0.02
PEG_EDGE_SPACING = 0.06
PEG_TOP_SPACING = 0.5
PEG_BOTTOM_SPACING = 0.3

# PEG_COL_SPACING = 0.3
# PEG_ROW_SPACING = PEG_COL_SPACING * 3**0.5 / 2  # sin(pi/3)
PEG_ROW_SPACING = 0.35 / 2
PEG_COL_SPACING = PEG_ROW_SPACING * 2.5

FIG_WIDTH = (
    (N_PEG_COLS - 0.5) * PEG_COL_SPACING
    + (N_PEG_COLS + 1) * 2 * PEG_RADIUS
    + 2 * PEG_EDGE_SPACING
)
FIG_HEIGHT = (
    (N_PEG_ROWS - 1) * PEG_ROW_SPACING
    + N_PEG_ROWS * 2 * PEG_RADIUS
    + PEG_BOTTOM_SPACING
    + PEG_TOP_SPACING
)
FIG_SCALE = 2

GRAVITY = -9.8  # m / s^2

# Appearance
BOARD_COLOR = "#222222"
PEG_COLOR = "#999999"
PUCK_COLOR = "#802020"

# Mechanical properties
PUCK_RADIUS = 0.1
PUCK_MASS = 0.1
PUCK_STIFFNESS = 1e4
PEG_STIFFNESS = PUCK_STIFFNESS
DAMPING = 0.2

# Initial state
PUCK_X = FIG_WIDTH / 2
PUCK_Y = FIG_HEIGHT - PUCK_RADIUS

# Time control
CLOCK_FREQ_SIM = 1000  # Hertz
CLOCK_PERIOD_SIM = 1 / float(CLOCK_FREQ_SIM)
CLOCK_FREQ_VIZ = 39  # Hertz

# Logging settings
LOGGING_LEVEL_SIM = logging.INFO
LOGGING_LEVEL_VIZ = logging.INFO
